### ISSUE TITLE
收不到邮件

### ISSUE THREAD

**Issue by Passerby1011** [oiov/vmail#11]
我搭建成功了，自己发的测试邮件我也能收到，在数据库里也能看到邮件，但是当我去拿临时邮箱注册一些东西是邮件就收不到了
比如我注册ai-pro时，我在cloudflare里能看到邮件记录，但是在数据库和网页看不到邮件
![image](https://github.com/oiov/vmail/assets/63802758/8fb8a919-a1fe-4154-b260-c437ce8221f8)
![image](https://github.com/oiov/vmail/assets/63802758/ae3f4929-c670-4710-9e0b-f9198c778b3b)

**Comment by oiov** [comment]
worker开日志检查

**Comment by Passerby1011** [comment]
![image](https://github.com/oiov/vmail/assets/63802758/a6ac515b-56d0-4eb7-9740-f2c046c7c7ac)
![image](https://github.com/oiov/vmail/assets/63802758/86639ec2-e190-4644-a27c-e3faa405e3be)
事实上我那你的提供的演示站的邮箱也收不到邮件
注册网站：ai-pro.org

**Comment by Passerby1011** [comment]
> worker开日志检查

你可用你自己的试试

**Comment by oiov** [comment]
确实不能收到， 我用gmail、qq邮箱、vmail分别注册了三次，只有gmail收到了，官方似乎对邮箱做了白名单。

**Comment by Passerby1011** [comment]
> 确实不能收到， 我用gmail、qq邮箱、vmail分别注册了三次，只有gmail收到了，官方似乎对邮箱做了白名单。

你手动在cloudflare添加一下转发，把邮件转发到其他邮箱是能收到的
