### ISSUE TITLE
DKIM status状态为none

### ISSUE THREAD

**Issue by mapxn** [oiov/vmail#13]
感谢作者提供这么棒的项目

完全按照作者的教程配置成功，尝试发送邮件，接收方（outlook）正常接到邮件，但提示xxx是未验证的发件人。

分别做了如下尝试：
1. 自己发给自己
2. 使用作者的演示站点发给自己

在Cloudflare的Email Routing页面查看接收日志：

显示**DKIM status: none**

<img width="1147" alt="image" src="https://github.com/oiov/vmail/assets/16299874/d2a7ec2d-038b-4279-a399-5f87607c122a">

不确定DKIM是否配置生效，有懂的朋友帮忙科普下么？

**Comment by wsgehaishan520** [comment]
应该不是立马生效，要过24h

**Comment by mapxn** [comment]
> 应该不是立马生效，要过24h

过了24h还是这样，用作者演示页面发也是同样的结果。所以应该不是生效时间问题

**Comment by mapxn** [comment]
参考[CF的文档](https://developers.cloudflare.com/pages/functions/plugins/mailchannels/)，看起来没什么问题。

**Comment by mapxn** [comment]
参考谷歌的DKIM [排查文档](https://support.google.com/a/answer/180504) 第四步：

> 验证是否已启用 DKIM 身份验证
向一名 Gmail 或 Google Workspace 用户发送一封电子邮件。（您无法通过向自己发送测试邮件来验证是否已启用 DKIM。）
在收件人的收件箱中打开相应邮件，找到完整的邮件标头。
注意：查看邮件标头的步骤因电子邮件应用而异。如需在 Gmail 中显示邮件标头，请点击回复旁边的更多图标  接着点击 显示原始邮件。
在邮件标头中，查找 Authentication-Results。接收邮件的服务会对传入邮件标头采用不同的格式，但 DKIM 结果应如下所示：DKIM=pass 或 DKIM=OK。
**如果邮件标头没有包含 DKIM 信息的行，则说明从您的网域发送的邮件未使用 DKIM 签名。**


使用演示站点给自己gmail发送邮件，并没有包含DKIM的行
<img width="927" alt="image" src="https://github.com/oiov/vmail/assets/16299874/ec14f82b-1246-42fc-b2c6-16153434ec47">

DKIM应该是没有生效的...

**Comment by oiov** [comment]
我这里是pass，DKIM我也不太熟，参考教配置的
![{9420BFD6-3F4C-43ee-84A7-9C207F1D1316}](https://github.com/oiov/vmail/assets/166131050/e2dfe8e6-5471-4718-8ea1-1a91b3ada83e)

**Comment by mapxn** [comment]
> 这里是pass，DKIM我也不太熟，参考教配置

这里的几个状态代表**发件方**的配置各项目是否开启。

三个PASS的这封邮件的发件人是通过vmail发送的么？我在演示站点（vmail.dev）尝试给自己不同的邮箱发，outlook这边显示DKIM: none, gmail这边显示未使用DKIM签名。

**Comment by oiov** [comment]
好吧也是none，看来确实没生效
