### ISSUE TITLE
各种问题，谢谢回答

### ISSUE THREAD

**Issue by hhtnFxQVwQntBLkULKjy** [oiov/vmail#16]
在接收邮件的教程中[https://github.com/oiov/vmail/blob/main/docs/receive-tutorial.md](url)，下面图片中的变量TURSO_DB_AUTH_TOKEN与后面在Vercel部署中的变量TURSO_DB_RO_AUTH_TOKEN是同一个值吗？
![屏幕截图 2024-06-05 204525](https://github.com/oiov/vmail/assets/20140506/95e8185a-ebd4-49d4-a064-2779b1232c0e)
![屏幕截图 2024-06-05 205521](https://github.com/oiov/vmail/assets/20140506/e3c7d30d-3fec-4129-aaaf-a9a85399d6ec)
按照教程一步步操作，接收不了邮件，
![屏幕截图 2024-06-05 210158](https://github.com/oiov/vmail/assets/20140506/e2f3f87a-c603-4d87-8071-4c6464c5db12)
![屏幕截图 2024-06-05 210234](https://github.com/oiov/vmail/assets/20140506/2c0e66b0-d401-4074-8b50-a1b212bb9836)

**Comment by hhtnFxQVwQntBLkULKjy** [comment]
上面第一张图里EMAIL_DOMAIN变量里面填的是访问面板所用的域名还是@xxxxx.com.像xxxxx.com或者xx.xxxxx.com这种邮箱的域名？

**Comment by hhtnFxQVwQntBLkULKjy** [comment]
turso只有读，没有写入
![屏幕截图 2024-06-05 213249](https://github.com/oiov/vmail/assets/20140506/a379ed8c-ef23-4529-923a-08daf827b7b3)

**Comment by oiov** [comment]
> TURSO_DB_AUTH_TOKEN与后面在Vercel部署中的变量TURSO_DB_RO_AUTH_TOKEN是同一个值吗？

是同一个

> 上面第一张图里EMAIL_DOMAIN变量里面填的是访问面板所用的域名还是@xxxxx.com.像xxxxx.com或者xx.xxxxx.com这种邮箱的域名？Worker触发器里面email-worker的路由需要更改吗？

xxxxx.com，参考示例值与文档
