### ISSUE TITLE
MailChannels will discontinue its free transaction email service for Cloudflare Workers

### ISSUE THREAD

**Issue by oiov** [oiov/vmail#17]
post: https://support.mailchannels.com/hc/en-us/articles/26814255454093-End-of-Life-Notice-Cloudflare-Workers?

在6月30日之后，Cloudflare Workers 通过免费 MailChannels API 发送的电子邮件将不再传送。 API 将开始拒绝来自未经授权的发件人的连接，并在您的 Worker 中返回错误（异常）。

cf 推荐替代发件方案：
- [How to send emails from a Worker using Resend.](https://content.cloudflare.com/NzEzLVhTQy05MTgAAAGTjjG8Ys3t-0DdnONPUX3DEWUQ0JiwyzqC1OyfvV-IiorCz78DtBfiDvw6cD6z1TPSRgvvkns=)
- [How to send emails from a Worker using Postmark.](https://content.cloudflare.com/NzEzLVhTQy05MTgAAAGTjjG8Yug2AWd1LqKcUs544u8TYOOj7hTFB9PFh7Svvwiu0BJTshNRTPt3c_HMxLArWT09EyA=)

**Comment by hhtnFxQVwQntBLkULKjy** [comment]
设置完成咋发不了邮件

**Comment by RootieButler** [comment]
可以用mailgun 嗎？ 每天100封正常使用很夠😁🥹🥹🥹
