### ISSUE TITLE
 Invalid email domain

### ISSUE THREAD

**Issue by Asakushen** [oiov/vmail#6]
按照文档部署好之后，出现Invalid email domain报错
![image](https://github.com/oiov/vmail/assets/74193315/bc99fbe6-5294-4471-8dd8-fba5767e94d5)
已经更换过其他域名，我的三个域名都出现这个错误

**Comment by oiov** [comment]
> 发现添加两个之后能正常出随机的邮箱地址了 xxx.xx,yyy.yy 这样添加后能正常显示邮箱地址了

只配一个域名会出现这种错误吗

**Comment by oiov** [comment]
已修复 716161b
